/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
import 'vue'
declare module 'vue' {
  export interface GlobalComponents {
    SvgIcon: import("vue").DefineComponent<{
        name: {
            type: import("vue").PropType<"black-domain" | "cheat-tool" | "dashboard" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "notification-email" | "organization" | "remote-app" | "search" | "signed-app" | "virtual-camera" | "vm-app" | "vpn-app">;
            default: string;
            required: true;
        };
    }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
        name: {
            type: import("vue").PropType<"black-domain" | "cheat-tool" | "dashboard" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "notification-email" | "organization" | "remote-app" | "search" | "signed-app" | "virtual-camera" | "vm-app" | "vpn-app">;
            default: string;
            required: true;
        };
    }>>, {
        name: "black-domain" | "cheat-tool" | "dashboard" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "notification-email" | "organization" | "remote-app" | "search" | "signed-app" | "virtual-camera" | "vm-app" | "vpn-app";
    }>;
  }
}
