/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"black-domain" | "cheat-tool" | "dashboard" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "notification-email" | "organization" | "remote-app" | "search" | "signed-app" | "virtual-camera" | "vm-app" | "vpn-app">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"black-domain" | "cheat-tool" | "dashboard" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "notification-email" | "organization" | "remote-app" | "search" | "signed-app" | "virtual-camera" | "vm-app" | "vpn-app">;
          default: string;
          required: true;
      };
  }>>, {
      name: "black-domain" | "cheat-tool" | "dashboard" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "notification-email" | "organization" | "remote-app" | "search" | "signed-app" | "virtual-camera" | "vm-app" | "vpn-app";
  }>;
  export const svgNames: ["black-domain", "cheat-tool", "dashboard", "fullscreen-exit", "fullscreen", "keyboard-down", "keyboard-enter", "keyboard-esc", "keyboard-up", "notification-email", "organization", "remote-app", "search", "signed-app", "virtual-camera", "vm-app", "vpn-app"];
  export type SvgName = "black-domain" | "cheat-tool" | "dashboard" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "notification-email" | "organization" | "remote-app" | "search" | "signed-app" | "virtual-camera" | "vm-app" | "vpn-app";
  export default SvgIcon;
}
